// Paths below are RAW on-disk paths under public/, never pre-encoded here.
// <Plate> resolves them through the build-time image manifest.
import type { GalleryLayout } from "./gallery-layout";

export type ProjectSection = {
  title: string;
  images: string[];
};

type ProjectCompare = {
  before: ProjectSection;
  after: ProjectSection;
};

export type Project = {
  slug: string;
  title: string;
  place: string;
  year: string;
  blurb: string;
  description: string;
  cover: string;
  /** Flat gallery. Rendered after `compare` and `sections` when present. */
  gallery?: string[];
  /** Named groups of plates, each with its own heading. */
  sections?: ProjectSection[];
  /** Side-by-side before/after columns (e.g. existing vs proposed). */
  compare?: ProjectCompare;
  /** How the plates are presented. Chosen from the material, see gallery-layout.ts. */
  layout?: GalleryLayout;
};

// Order here is the order of the filter tabs on /projects.
export const categories = [
  "all",
  "commercial",
  "residential",
  "others",
  "special-planning",
  "urban-planning",
  "fashion",
  "landscape",
  "logo-branding",
] as const;

export type Cat = (typeof categories)[number];

export const categoryLabel: Record<string, string> = {
  all: "All",
  commercial: "Commercial",
  residential: "Residential",
  others: "Institutional",
  "special-planning": "Special Planning",
  "urban-planning": "Urban Planning",
  fashion: "Fashion",
  landscape: "Landscape",
  "logo-branding": "Logo & Branding",
};

export const projectsByCategory: Record<string, Project[]> = {
  commercial: [
    {
      slug: "artisan-bakery",
      layout: "grid",
      title: "Artisan Bakery",
      place: "Commercial",
      year: "",
      blurb: "A boutique bakery interior shaped around craft and warmth.",
      description:
        "A commercial interior for an artisan bakery. The plan reads as a calm display floor, with material textures and lighting tuned to the rhythm of fresh-baked product on display.",
      cover: "/projects/commercial/artisanbakery/a1.jpeg",
      gallery: [
        "/projects/commercial/artisanbakery/a1.jpeg",
        "/projects/commercial/artisanbakery/8.jpeg",
        "/projects/commercial/artisanbakery/a2.jpeg",
        "/projects/commercial/artisanbakery/a3.jpeg",
        "/projects/commercial/artisanbakery/a4.jpeg",
        "/projects/commercial/artisanbakery/a5.jpeg",
      ],
    },
    {
      slug: "arena-fitness-club",
      layout: "grid",
      title: "Arena Fitness Club",
      place: "Commercial Interior",
      year: "",
      blurb: "An industrial, rusty fitness interior in Parachinar City.",
      description:
        "A commercial interior for Arena Fitness Club, located in Parachinar City. The space is shaped around an industrial and rusty design language, with a palette of brown, gray and black tones tying floor, structure and lighting into a single grounded atmosphere.",
      cover: "/projects/commercial/arenafitness/2.png",
      gallery: [
        "/projects/commercial/arenafitness/2.png",
        "/projects/commercial/arenafitness/4.jpeg",
        "/projects/commercial/arenafitness/5.png",
        "/projects/commercial/arenafitness/6.jpeg",
        "/projects/commercial/arenafitness/9.png",
        "/projects/commercial/arenafitness/10.png",
        "/projects/commercial/arenafitness/11.png",
        "/projects/commercial/arenafitness/12.png",
      ],
    },
  ],
  residential: [
    {
      slug: "visal-home",
      layout: "grid",
      title: "Visal Home",
      place: "Residential",
      year: "",
      blurb: "A family residence balancing privacy and openness.",
      description:
        "A residential project organised around daylit communal volumes and quieter, sheltered private wings. The composition keeps proportion and material restraint at the centre.",
      cover: "/projects/residential/visalhome/v1.jpeg",
      gallery: [
        "/projects/residential/visalhome/v1.jpeg",
        "/projects/residential/visalhome/v2.jpeg",
        "/projects/residential/visalhome/v3.jpeg",
        "/projects/residential/visalhome/v4.jpeg",
        "/projects/residential/visalhome/v6.jpeg",
      ],
    },
    {
      slug: "bazar-home",
      layout: "editorial",
      title: "Bazar Home",
      place: "Residential",
      year: "",
      blurb: "A residence threaded between street life and inner courtyards.",
      description:
        "A residential project that mediates between an active urban street edge and quiet interior rooms, with daylight and air pulled deep into the plan through a small set of measured openings.",
      cover: "/projects/residential/bazarhome/b1.jpeg",
      gallery: [
        "/projects/residential/bazarhome/b1.jpeg",
        "/projects/residential/bazarhome/a2.jpeg",
        "/projects/residential/bazarhome/a3.jpeg",
      ],
    },
    {
      slug: "home",
      layout: "grid",
      title: "Home",
      place: "Residential",
      year: "",
      blurb: "A family house in brick and board-marked concrete.",
      description:
        "A residential house organised behind a long horizontal canopy. Brick and concrete are held in clear bands across the elevation, with the entrance stair and its lit threshold set at the centre of the composition.",
      cover: "/projects/residential/home/front elevation'.png",
      gallery: [
        "/projects/residential/home/front elevation'.png",
        "/projects/residential/home/WhatsApp Image 2026-08-29 at 3.53.35 AM.jpeg",
        "/projects/residential/home/WhatsApp Image 2026-08-29 at 3.53.36 AM.jpeg",
        "/projects/residential/home/WhatsApp Image 2026-08-29 at 3.53.36 AM (1).jpeg",
        "/projects/residential/home/WhatsApp Image 2026-08-29 at 3.54.03 AM.jpeg",
      ],
    },
    {
      slug: "interior",
      layout: "diptych",
      title: "Interior",
      place: "Residential",
      year: "",
      blurb: "A wabi sabi interior for a house in Parachinar.",
      description:
        "An interior scheme for a house in the Kurram region, worked out room by room against a fixed palette of lime plaster, natural wood, cane, stone tile and linen. The boards carry the material palette, lighting strategy and the concept overlay plan alongside the room views.",
      cover: "/projects/residential/interior/frint view.png",
      gallery: [
        "/projects/residential/interior/frint view.png",
        "/projects/residential/interior/bed.png",
        "/projects/residential/interior/ChatGPT Image Apr 22, 2026, 03_31_21 PM.png",
        "/projects/residential/interior/ChatGPT Image Apr 22, 2026, 03_34_46 PM.png",
        "/projects/residential/interior/ChatGPT Image Apr 22, 2026, 03_54_53 PM.png",
        "/projects/residential/interior/fv.png",
        "/projects/residential/interior/gr.png",
        "/projects/residential/interior/LAYOUT.png",
      ],
    },
  ],
  others: [
    {
      slug: "a-walk",
      layout: "diptych",
      title: "A Walk",
      place: "Institutional",
      year: "",
      blurb: "An elevated red walk threaded over an existing brick campus.",
      description:
        "A raised walk in red steel carried over and between the existing brick buildings, turning the route between them into the building itself. The plates run from the master plan, where the walk is drawn as a single red line through the block, to level diagrams and evening views from under the structure.",
      cover: "/projects/institutional/a walk/AXO.jpeg",
      gallery: [
        "/projects/institutional/a walk/AXO.jpeg",
        "/projects/institutional/a walk/5'.png",
        "/projects/institutional/a walk/8.png",
        "/projects/institutional/a walk/9.png",
        "/projects/institutional/a walk/10.png",
        "/projects/institutional/a walk/88 (1).png",
        "/projects/institutional/a walk/88 (2).png",
        "/projects/institutional/a walk/88 (3).png",
        "/projects/institutional/a walk/88 (4).png",
        "/projects/institutional/a walk/88 (5).png",
        "/projects/institutional/a walk/88 (6).png",
        "/projects/institutional/a walk/88 (7).png",
        "/projects/institutional/a walk/88 (8).png",
        "/projects/institutional/a walk/ISO N.jpeg",
        "/projects/institutional/a walk/ISO.jpeg",
        "/projects/institutional/a walk/levels.png",
        "/projects/institutional/a walk/qareeb.png",
      ],
    },
    {
      slug: "amphitheater",
      layout: "diptych",
      title: "Amphitheater",
      place: "Institutional",
      year: "",
      blurb: "A sunken circular amphitheatre cut into a campus courtyard.",
      description:
        "A circular amphitheatre sunk into the ground between existing brick faculties, ringed by seating and held under mature trees. The plates move from master plan and isometric to views taken from the auditorium steps and from Fine Arts.",
      cover: "/projects/institutional/amphitheater/view from audi steps.png",
      gallery: [
        "/projects/institutional/amphitheater/view from audi steps.png",
        "/projects/institutional/amphitheater/iso metric view.png",
        "/projects/institutional/amphitheater/masterplan.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 164432.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 164530.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 164602.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 164738.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 164950.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 165228.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 165819.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 165958.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 170158.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 170307.png",
        "/projects/institutional/amphitheater/Screenshot 2024-06-03 170316.png",
        "/projects/institutional/amphitheater/view from finearts.png",
        "/projects/institutional/amphitheater/w from audi steps.png",
      ],
    },
    {
      slug: "parasitic-approach",
      layout: "diptych",
      title: "Parasitic Approach",
      place: "Institutional",
      year: "",
      blurb: "A new structure grafted onto an existing arcaded building.",
      description:
        "A study in attaching rather than replacing. New floors and stairs clamp onto the arcaded facade of an existing building and cantilever past it. The plates are mostly white massing studies and sections cut through the point where old and new meet.",
      cover: "/projects/institutional/parasitic approach/human eye view.png",
      gallery: [
        "/projects/institutional/parasitic approach/human eye view.png",
        "/projects/institutional/parasitic approach/FRTRVRVF.png",
        "/projects/institutional/parasitic approach/rendor 11.png",
        "/projects/institutional/parasitic approach/rendor2222.png",
        "/projects/institutional/parasitic approach/sec2.png",
        "/projects/institutional/parasitic approach/sectiommmm.png",
        "/projects/institutional/parasitic approach/section 1.png",
        "/projects/institutional/parasitic approach/sectionnnn.png",
        "/projects/institutional/parasitic approach/WhatsApp Image 2024-05-26 at 02.34.34_41a2ea16.jpg",
      ],
    },
    {
      slug: "student-center",
      layout: "diptych",
      title: "Student Center",
      place: "Institutional",
      year: "",
      blurb: "A planted roof over a sunken lawn and a columned undercroft.",
      description:
        "A student centre set among the trees of Nasir Bagh. A planted roof is carried on slender columns over a shaded undercroft, and the ground is cut away into a sunken circular lawn. The plates cover the approach, studio and exhibition space, the stairs, and the stalls that occupy the roof.",
      cover: "/projects/institutional/student center/studio space.png",
      gallery: [
        "/projects/institutional/student center/studio space.png",
        "/projects/institutional/student center/rooftop.png",
        "/projects/institutional/student center/2.png",
        "/projects/institutional/student center/3.png",
        "/projects/institutional/student center/amhphitheater entrance in a way.png",
        "/projects/institutional/student center/amphitheater entrance.png",
        "/projects/institutional/student center/exibation space subah.png",
        "/projects/institutional/student center/indeed.png",
        "/projects/institutional/student center/iso.jpg",
        "/projects/institutional/student center/more indeed.png",
        "/projects/institutional/student center/nasir bagh around the trees.png",
        "/projects/institutional/student center/proposal 3.jpg",
        "/projects/institutional/student center/staircase.png",
        "/projects/institutional/student center/stairrcase.png",
        "/projects/institutional/student center/stairrrcase.png",
        "/projects/institutional/student center/stalls on rooftop.png",
      ],
    },
    {
      slug: "thesis",
      layout: "contact-sheet",
      title: "Thesis",
      place: "Institutional",
      year: "",
      blurb: "A thesis project organised around a top-lit central courtyard.",
      description:
        "The full thesis set. A large institutional building is organised around a central courtyard lit from a circular oculus, with stairs and galleries wrapping it at every level. The sheets run from the site and parking approach through massing to the interior of the courtyard itself.",
      cover: "/projects/institutional/thesis/main courtyard.png",
      gallery: [
        "/projects/institutional/thesis/main courtyard.png",
        "/projects/institutional/thesis/1.png",
        "/projects/institutional/thesis/2.png",
        "/projects/institutional/thesis/3.png",
        "/projects/institutional/thesis/4.png",
        "/projects/institutional/thesis/5.png",
        "/projects/institutional/thesis/6.png",
        "/projects/institutional/thesis/7.png",
        "/projects/institutional/thesis/8.png",
        "/projects/institutional/thesis/9.png",
        "/projects/institutional/thesis/10.png",
        "/projects/institutional/thesis/11 (1).png",
        "/projects/institutional/thesis/11 (2).png",
        "/projects/institutional/thesis/11 (3).png",
        "/projects/institutional/thesis/11.png",
        "/projects/institutional/thesis/12.png",
        "/projects/institutional/thesis/20 (1).png",
        "/projects/institutional/thesis/20 (2).png",
        "/projects/institutional/thesis/20 (3).png",
        "/projects/institutional/thesis/20 (4).png",
        "/projects/institutional/thesis/20 (5).png",
        "/projects/institutional/thesis/20 (6).png",
        "/projects/institutional/thesis/20 (7).png",
        "/projects/institutional/thesis/20.png",
        "/projects/institutional/thesis/22 (1).png",
        "/projects/institutional/thesis/22 (2).png",
        "/projects/institutional/thesis/22 (3).png",
        "/projects/institutional/thesis/22 (4).png",
        "/projects/institutional/thesis/22 (5).png",
        "/projects/institutional/thesis/22 (6).png",
        "/projects/institutional/thesis/22 (7).png",
        "/projects/institutional/thesis/30 (1).png",
        "/projects/institutional/thesis/30 (2).png",
        "/projects/institutional/thesis/30 (3).png",
        "/projects/institutional/thesis/33 (1).png",
        "/projects/institutional/thesis/33 (2).png",
        "/projects/institutional/thesis/33 (3).png",
        "/projects/institutional/thesis/33 (4).png",
        "/projects/institutional/thesis/33 (5).png",
        "/projects/institutional/thesis/33 (6).png",
        "/projects/institutional/thesis/33 (7).png",
        "/projects/institutional/thesis/33 (8).png",
        "/projects/institutional/thesis/33 (9).png",
        "/projects/institutional/thesis/55 (1).png",
        "/projects/institutional/thesis/55 (2).png",
        "/projects/institutional/thesis/55 (3).png",
        "/projects/institutional/thesis/55 (4).png",
        "/projects/institutional/thesis/55 (5).png",
        "/projects/institutional/thesis/55 (6).png",
        "/projects/institutional/thesis/55 (7).png",
        "/projects/institutional/thesis/55 (8).png",
        "/projects/institutional/thesis/55 (9).png",
        "/projects/institutional/thesis/55 (10).png",
        "/projects/institutional/thesis/55 (11).png",
        "/projects/institutional/thesis/iso.png",
        "/projects/institutional/thesis/paking acees ramp.png",
        "/projects/institutional/thesis/parking to clg view.png",
      ],
    },
  ],
  "special-planning": [
    {
      slug: "sacred-geometry",
      layout: "editorial",
      title: "Sacred Geometry",
      place: "Special Planning",
      year: "",
      blurb: "Geometry as a generative language for inhabited space.",
      description:
        "A studio investigation into proportion, symmetry, and the underlying geometric patterns that organise architecture, from the scale of a single room up to a village fabric.",
      cover: "/projects/specialplanning/sacredgeometry/backdesign/s4.png",
      gallery: [
        "/projects/specialplanning/sacredgeometry/backdesign/s4.png",
        "/projects/specialplanning/sacredgeometry/backdesign/t1.jpeg",
        "/projects/specialplanning/sacredgeometry/backdesign/t6.jpeg",
        "/projects/specialplanning/sacredgeometry/backdesign/t15.png",
        "/projects/specialplanning/sacredgeometry/backdesign/t16.png",
        "/projects/specialplanning/sacredgeometry/backdesign/t17.png",
        "/projects/specialplanning/sacredgeometry/backdesign/t18.png",
        "/projects/specialplanning/sacredgeometry/backdesign/t19.png",
        "/projects/specialplanning/sacredgeometry/backdesign/t20.png",
        "/projects/specialplanning/sacredgeometry/backdesign/s2.jpeg",
        "/projects/specialplanning/sacredgeometry/backdesign/s3.jpeg",
      ],
    },
  ],
  "urban-planning": [
    {
      slug: "panahgah",
      layout: "cinematic",
      title: "Panahgah",
      place: "Urban Planning",
      year: "",
      blurb: "A shelter proposal read at the scale of the city block.",
      description:
        "An urban proposal for Panahgah, a place of shelter. The plates move from master plan and detail plans through exploded axonometrics and sections to the spatial views that test the proposal at eye level.",
      cover: "/projects/urban/panahgah/PANAHGAH FINAL PRE.jpg",
      gallery: [
        "/projects/urban/panahgah/PANAHGAH FINAL PRE.jpg",
        "/projects/urban/panahgah/MASTER PLAN.jpg",
        "/projects/urban/panahgah/MASTTTTTTTTTTT.png",
        "/projects/urban/panahgah/detail plan.png",
        "/projects/urban/panahgah/EXPLODED AXONOMO.png",
        "/projects/urban/panahgah/{3D}.jpg",
        "/projects/urban/panahgah/HAMMAD 1.jpg",
        "/projects/urban/panahgah/HA 2.jpg",
        "/projects/urban/panahgah/HA 3.jpg",
        "/projects/urban/panahgah/HA 4.jpg",
        "/projects/urban/panahgah/HA 5[1].jpg",
        "/projects/urban/panahgah/HA 6.jpg",
        "/projects/urban/panahgah/HA 7.jpg",
        "/projects/urban/panahgah/HA 8.jpg",
        "/projects/urban/panahgah/HA 9.jpg",
        "/projects/urban/panahgah/HAAAA13.jpg",
        "/projects/urban/panahgah/HAAAA  14.jpg",
        "/projects/urban/panahgah/HAM 15.jpg",
        "/projects/urban/panahgah/HAMM 16.jpg",
        "/projects/urban/panahgah/HAA 19.jpg",
        "/projects/urban/panahgah/GHGHGH.png",
        "/projects/urban/panahgah/RTRTRTRETETET.png",
        "/projects/urban/panahgah/AASASASASASASA.jpg",
        "/projects/urban/panahgah/HAHAAHHAAHAAH.jpg",
        "/projects/urban/panahgah/huuuu.jpg",
        "/projects/urban/panahgah/1131313.jpg",
        "/projects/urban/panahgah/121212121.jpg",
        "/projects/urban/panahgah/12121212122131324.jpg",
      ],
    },
    {
      slug: "pedestrianizing-anarkali",
      title: "Pedestrianizing Anarkali",
      place: "Urban Planning",
      year: "",
      blurb: "Anarkali's foot street, read as existing condition and proposal.",
      description:
        "An urban study of Anarkali that pedestrianises the foot street. The drawings are set out as a direct comparison, the existing condition on one side and the proposed intervention on the other, across plan, axonometric, section and the street-level electrical system.",
      cover: "/projects/urban/pedestrianzing_anarkali/proposed/1.png",
      compare: {
        before: {
          title: "Existing",
          images: [
            "/projects/urban/pedestrianzing_anarkali/existing/existing plan.png",
            "/projects/urban/pedestrianzing_anarkali/existing/axo.png",
            "/projects/urban/pedestrianzing_anarkali/existing/kocho.png",
            "/projects/urban/pedestrianzing_anarkali/existing/electric systrem in anarkali foot street vs proposal.png",
            "/projects/urban/pedestrianzing_anarkali/existing/isoooooo.png",
            "/projects/urban/pedestrianzing_anarkali/existing/view 1.png",
            "/projects/urban/pedestrianzing_anarkali/existing/21.png",
            "/projects/urban/pedestrianzing_anarkali/existing/7.png",
            "/projects/urban/pedestrianzing_anarkali/existing/vfebetb egbvw ad.png",
            "/projects/urban/pedestrianzing_anarkali/existing/WhatsApp Image 2024-05-30 at 07.54.58_cec1b120.jpg",
          ],
        },
        after: {
          title: "Proposed",
          images: [
            "/projects/urban/pedestrianzing_anarkali/proposed/proposal plan.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/axoooooooo aftrt.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/pocho.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/electric systrem in anarkali foot street.jpg",
            "/projects/urban/pedestrianzing_anarkali/proposed/1.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/2.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/3.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/4.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/gfrvgdvgsv.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/sec.png",
            "/projects/urban/pedestrianzing_anarkali/proposed/sec blow up.png",
          ],
        },
      },
    },
    {
      slug: "reimaging-co-existance",
      layout: "diptych",
      title: "Reimaging Co Existance",
      place: "Urban Planning",
      year: "",
      blurb: "A master plan where agriculture, livestock and workshop co-exist.",
      description:
        "An urban proposal that reimagines co-existence between productive landscapes and settlement. The master plans and axonometric models set agriculture, livestock, textile and workshop programmes alongside the shared centre and its parking.",
      cover: "/projects/urban/reimaging co existance/masterplan.png",
      gallery: [
        "/projects/urban/reimaging co existance/masterplan.png",
        "/projects/urban/reimaging co existance/MASTEER PLEEN.jpg",
        "/projects/urban/reimaging co existance/taqreeban masterplan.png",
        "/projects/urban/reimaging co existance/masterrrrrrrrrrr plan Taqreeban.jpg",
        "/projects/urban/reimaging co existance/CENTRE.png",
        "/projects/urban/reimaging co existance/AGRICULTURE PART.jpg",
        "/projects/urban/reimaging co existance/agriculture model axo.png",
        "/projects/urban/reimaging co existance/BIO GAS LIVESTOCK PART.jpg",
        "/projects/urban/reimaging co existance/livestock model axo.png",
        "/projects/urban/reimaging co existance/livestock model axo 2.png",
        "/projects/urban/reimaging co existance/jungle model axo.png",
        "/projects/urban/reimaging co existance/TEXTILE PART ISO.jpg",
        "/projects/urban/reimaging co existance/WORKSHOP PART ISO.jpg",
        "/projects/urban/reimaging co existance/PARKING.png",
        "/projects/urban/reimaging co existance/view 1.png",
        "/projects/urban/reimaging co existance/view 11.png",
        "/projects/urban/reimaging co existance/viewn2.png",
        "/projects/urban/reimaging co existance/1.png",
        "/projects/urban/reimaging co existance/2.png",
        "/projects/urban/reimaging co existance/22.png",
        "/projects/urban/reimaging co existance/33.png",
        "/projects/urban/reimaging co existance/44.png",
      ],
    },
  ],
  fashion: [
    {
      slug: "fashion-design",
      layout: "diptych",
      title: "Fashion Design",
      place: "Fashion",
      year: "",
      blurb: "Team kit design: crests, numbering and pattern work.",
      description:
        "A series of team kits designed by the studio, each drawn front and back. Crest, name block and numbering are set against pattern work that runs from flat colour and checks to contour fields and traditional woven borders.",
      cover: "/projects/fashiondesign/3.jpeg",
      gallery: [
        "/projects/fashiondesign/3.jpeg",
        "/projects/fashiondesign/1.jpeg",
        "/projects/fashiondesign/2.jpeg",
        "/projects/fashiondesign/4.jpeg",
        "/projects/fashiondesign/5.jpeg",
        "/projects/fashiondesign/6.jpeg",
        "/projects/fashiondesign/7.jpeg",
        "/projects/fashiondesign/8.jpeg",
        "/projects/fashiondesign/9.jpeg",
        "/projects/fashiondesign/10.jpeg",
        "/projects/fashiondesign/11.jpeg",
        "/projects/fashiondesign/12.jpeg",
        "/projects/fashiondesign/13.jpeg",
        "/projects/fashiondesign/14.jpeg",
        "/projects/fashiondesign/15.jpeg",
      ],
    },
    {
      slug: "furniture-design",
      layout: "diptych",
      title: "Furniture Design",
      place: "Fashion",
      year: "",
      blurb: "Walls, frames and fittings, from working drawing to render.",
      description:
        "A furniture and fitted-joinery series developed for interiors of the studio's own projects. Shown as finished visuals alongside the working drawings that set out each wall, frame and module.",
      cover: "/projects/furnituredesign/visuals/1.png",
      sections: [
        {
          title: "Visuals",
          images: [
            "/projects/furnituredesign/visuals/1.png",
            "/projects/furnituredesign/visuals/2.png",
            "/projects/furnituredesign/visuals/3.png",
            "/projects/furnituredesign/visuals/4.png",
            "/projects/furnituredesign/visuals/5.png",
            "/projects/furnituredesign/visuals/6.png",
            "/projects/furnituredesign/visuals/7.png",
            "/projects/furnituredesign/visuals/9.png",
            "/projects/furnituredesign/visuals/10.png",
            "/projects/furnituredesign/visuals/11.png",
            "/projects/furnituredesign/visuals/11 (1).png",
            "/projects/furnituredesign/visuals/11 (3).png",
            "/projects/furnituredesign/visuals/11c.png",
            "/projects/furnituredesign/visuals/13a.png",
            "/projects/furnituredesign/visuals/13d.png",
            "/projects/furnituredesign/visuals/14b.png",
          ],
        },
        {
          title: "Drawings",
          images: [
            "/projects/furnituredesign/drawings/1.png",
            "/projects/furnituredesign/drawings/front wall.png",
            "/projects/furnituredesign/drawings/artisan wall.png",
            "/projects/furnituredesign/drawings/interective wall.png",
            "/projects/furnituredesign/drawings/fabinachi wall.png",
            "/projects/furnituredesign/drawings/fabinachoi front wall.png",
            "/projects/furnituredesign/drawings/khambeer wall.png",
            "/projects/furnituredesign/drawings/khambeer.png",
            "/projects/furnituredesign/drawings/frame.png",
            "/projects/furnituredesign/drawings/frame 2.png",
            "/projects/furnituredesign/drawings/dim.jpeg",
          ],
        },
      ],
    },
  ],
  landscape: [
    {
      slug: "ravi-jungle-shelter-houses",
      layout: "diptych",
      title: "Ravi Jungle Shelter Houses",
      place: "Landscape",
      year: "",
      blurb: "Shelter houses read against the Ravi and the settlement beside it.",
      description:
        "A landscape study along the Ravi. Hand-drawn site maps set the baradari, the informal settlement and the kachi abadi against primary roads, urban nullahs and remaining green cover, and the shelter itself is drawn as a raised circular platform built around an existing tree.",
      cover: "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.42.55 PM.jpeg",
      gallery: [
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.42.55 PM.jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.47.32 PM (1).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.47.32 PM (2).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.47.32 PM (3).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.47.32 PM (4).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.47.32 PM (5).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.47.32 PM.jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.57.25 PM (1).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.57.25 PM (2).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.57.25 PM (3).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.57.25 PM (4).jpeg",
        "/projects/landscape/landscape design/Ravi jungle shelter houses/WhatsApp Image 2026-08-07 at 1.57.25 PM.jpeg",
      ],
    },
    {
      slug: "roohi-gate",
      layout: "diptych",
      title: "Roohi Gate",
      place: "Landscape",
      year: "",
      blurb: "A ceremonial gate and its approach at Rahim Yar Khan Garrison.",
      description:
        "A gateway and approach landscape for the garrison at Rahim Yar Khan. A water channel runs the length of the boulevard up to the gate, held between planted verges and low masonry, with the existing avenue of trees kept as the frame.",
      cover: "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/4.png",
      gallery: [
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/4.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/1.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/2.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/3.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/5.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/6.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/7.png",
        "/projects/landscape/landscape design/Roohi gate Rahim Yar Khan Garison/site.png",
      ],
    },
    {
      slug: "tauqali-house",
      layout: "diptych",
      title: "Tauqali House",
      place: "Landscape",
      year: "",
      blurb: "A house and the jama it shares with its neighbours.",
      description:
        "A house planned around the jama, the shared forecourt that sits in front of two or three homes and carries the weddings, funerals and everyday gathering of the households around it. The plates run from master plan and detailed jama plan through sections to isometric views of the whole site.",
      cover: "/projects/landscape/landscape design/tauqali house A home with JAMA/REND JAMA.png",
      gallery: [
        "/projects/landscape/landscape design/tauqali house A home with JAMA/REND JAMA.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/AXONO METRIC SEC HOME.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/DETAIELD HOMES PLANA.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/DETAILED JAMA PLAN.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/DETAILED PLAN.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/DETAILED PLANS HOMES.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/HOME PLAN DETAILED.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/HOME REND PLAN.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/HOME SEC 2.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/iso-section.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/ISOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/IZOOOOOO.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/JAMA PLAN DETAILED.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/jama rend.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/MASTER PLAN JAMA.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/MASTERPLAN.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/MMMMMMMMMMMMMMMASTER.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/Screenshot 2024-10-18 223928.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/SEC HOME 1.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/SEC SITE QEBLA SIDE.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/sec style1.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/site iso.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/V1.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/v2.png",
        "/projects/landscape/landscape design/tauqali house A home with JAMA/v3.png",
      ],
    },
  ],
  "logo-branding": [
    {
      slug: "artisan-bakerz",
      layout: "diptych",
      title: "Artisan Bakerz",
      place: "Logo & Branding",
      year: "",
      blurb: "A mark built on a grid, then cut into the wall it belongs to.",
      description:
        "Identity for Artisan Bakerz. The mark is constructed geometrically, a rotated square worked over a grid, and tested through its variants before being carved into the timber panelling of the bakery interior the studio designed.",
      cover: "/projects/logoandbranding/ARTISAN BAKERZ/main.jpeg",
      gallery: [
        "/projects/logoandbranding/ARTISAN BAKERZ/main.jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/1.png",
        "/projects/logoandbranding/ARTISAN BAKERZ/2.png",
        "/projects/logoandbranding/ARTISAN BAKERZ/logo on wall.png",
        "/projects/logoandbranding/ARTISAN BAKERZ/MORE INDEED.png",
        "/projects/logoandbranding/ARTISAN BAKERZ/more interesting.png",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.52.45 PM.jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.52.46 PM (1).jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.52.46 PM (2).jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.52.46 PM.jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.53.22 PM (2).jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.53.22 PM.jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.53.23 PM (1).jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.53.23 PM (2).jpeg",
        "/projects/logoandbranding/ARTISAN BAKERZ/WhatsApp Image 2026-09-05 at 1.53.23 PM.jpeg",
      ],
    },
  ],
};
