/**
 * Moves every file under public/ that the site never references into unused/,
 * keeping its folder structure. Nothing is deleted.
 *
 *   node scripts/move-unused.mjs          list what would move
 *   node scripts/move-unused.mjs --apply  actually move it
 */
import { readdirSync, statSync, readFileSync, mkdirSync, renameSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";

const APPLY = process.argv.includes("--apply");

/** Every file under a directory, as paths relative to public/. */
function walk(dir, base, acc = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      if (name === "_opt") continue; // generated, not source
      walk(p, base, acc);
    } else {
      acc.push(
        "/" +
          p
            .slice(base.length + 1)
            .split("\\")
            .join("/"),
      );
    }
  }
  return acc;
}

// Every "/..." string literal anywhere in the source counts as a reference.
// This catches the data modules, the hero `slides`, team photos and the logo
// without having to enumerate them by hand.
//
// Only .ts/.tsx are scanned. image-manifest.json is generated by walking
// public/, so it holds a key for every file there and would make even a
// genuinely orphaned image look referenced.
const exact = new Set();
const prefixes = new Set();

(function scan(dir) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) {
      scan(p);
      continue;
    }
    if (!/\.tsx?$/.test(name)) continue;

    let text = readFileSync(p, "utf8");
    // Expand `const DIR = "/Thinking/brainstorming"` into the `${DIR}/x.jpg`
    // templates that use it, so those paths read as ordinary literals.
    const consts = {};
    for (const m of text.matchAll(/const\s+(\w+)\s*=\s*["'`]([^"'`\n]*)["'`]/g))
      consts[m[1]] = m[2];
    text = text.replace(/\$\{(\w+)\}/g, (whole, n) => (n in consts ? consts[n] : whole));

    // Match each quote style separately. A path inside a double-quoted string
    // may legitimately contain an apostrophe ("front elevation'.png"), and a
    // combined character class truncates it and calls a live file unused.
    for (const re of [/"(\/[^"\n]*)"/g, /'(\/[^'\n]*)'/g, /`([^`]*)`/g]) {
      for (const m of text.matchAll(re)) {
        const raw = m[1];
        if (!raw.startsWith("/")) continue;
        // A path still holding `${...}` is computed, e.g. the ravi sketches are
        // built with a padded counter. Keep the literal head as a prefix: every
        // file under it counts as referenced, which is the safe direction.
        const computed = raw.indexOf("${");
        if (computed === -1) exact.add(decodeURIComponent(raw));
        else prefixes.add(decodeURIComponent(raw.slice(0, computed)));
      }
    }
  }
})("src");

const all = walk("public", "public");
const unused = all.filter(
  (f) => !exact.has(f) && ![...prefixes].some((p) => p.length > 12 && f.startsWith(p)),
);

const bytes = (f) => statSync(join("public", f)).size;
const byFolder = {};
for (const f of unused) {
  const key = f.split("/").slice(0, 3).join("/");
  byFolder[key] = (byFolder[key] ?? 0) + bytes(f);
}

console.log(
  `${all.length} files under public/, ` +
    `${exact.size} referenced paths and ${prefixes.size} computed prefixes in src/`,
);
console.log(`${unused.length} unreferenced files:\n`);
for (const f of unused) console.log(`  ${f}`);
if (unused.length) console.log();
for (const [k, v] of Object.entries(byFolder).sort((a, b) => b[1] - a[1]))
  console.log(`  ${(v / 1048576).toFixed(1).padStart(7)} MB  ${k}`);
console.log(`\n  ${(unused.reduce((s, f) => s + bytes(f), 0) / 1048576).toFixed(1)} MB total`);

if (!APPLY) {
  console.log("\n(dry run, nothing moved. re-run with --apply)");
} else {
  for (const f of unused) {
    const from = join("public", f);
    const to = join("unused", f);
    mkdirSync(dirname(to), { recursive: true });
    if (!existsSync(to)) renameSync(from, to);
  }
  console.log(`\nmoved ${unused.length} files into unused/`);
}
