/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThinkingRouteImport } from './routes/thinking'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThinkingIndexRouteImport } from './routes/thinking.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ThinkingSlugRouteImport } from './routes/thinking.$slug'
import { Route as ThinkingSlugIndexRouteImport } from './routes/thinking.$slug.index'
import { Route as ThinkingSlugSubRouteImport } from './routes/thinking.$slug.$sub'
import { Route as ProjectsCategorySlugRouteImport } from './routes/projects.$category.$slug'

const ThinkingRoute = ThinkingRouteImport.update({
  id: '/thinking',
  path: '/thinking',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThinkingIndexRoute = ThinkingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThinkingRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ThinkingSlugRoute = ThinkingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ThinkingRoute,
} as any)
const ThinkingSlugIndexRoute = ThinkingSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ThinkingSlugRoute,
} as any)
const ThinkingSlugSubRoute = ThinkingSlugSubRouteImport.update({
  id: '/$sub',
  path: '/$sub',
  getParentRoute: () => ThinkingSlugRoute,
} as any)
const ProjectsCategorySlugRoute = ProjectsCategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/thinking': typeof ThinkingRouteWithChildren
  '/thinking/$slug': typeof ThinkingSlugRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/thinking/': typeof ThinkingIndexRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/thinking/$slug/$sub': typeof ThinkingSlugSubRoute
  '/thinking/$slug/': typeof ThinkingSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsIndexRoute
  '/thinking': typeof ThinkingIndexRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/thinking/$slug/$sub': typeof ThinkingSlugSubRoute
  '/thinking/$slug': typeof ThinkingSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/thinking': typeof ThinkingRouteWithChildren
  '/thinking/$slug': typeof ThinkingSlugRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/thinking/': typeof ThinkingIndexRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
  '/thinking/$slug/$sub': typeof ThinkingSlugSubRoute
  '/thinking/$slug/': typeof ThinkingSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/people'
    | '/projects'
    | '/thinking'
    | '/thinking/$slug'
    | '/projects/'
    | '/thinking/'
    | '/projects/$category/$slug'
    | '/thinking/$slug/$sub'
    | '/thinking/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/people'
    | '/projects'
    | '/thinking'
    | '/projects/$category/$slug'
    | '/thinking/$slug/$sub'
    | '/thinking/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/people'
    | '/projects'
    | '/thinking'
    | '/thinking/$slug'
    | '/projects/'
    | '/thinking/'
    | '/projects/$category/$slug'
    | '/thinking/$slug/$sub'
    | '/thinking/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ThinkingRoute: typeof ThinkingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thinking': {
      id: '/thinking'
      path: '/thinking'
      fullPath: '/thinking'
      preLoaderRoute: typeof ThinkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thinking/': {
      id: '/thinking/'
      path: '/'
      fullPath: '/thinking/'
      preLoaderRoute: typeof ThinkingIndexRouteImport
      parentRoute: typeof ThinkingRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/thinking/$slug': {
      id: '/thinking/$slug'
      path: '/$slug'
      fullPath: '/thinking/$slug'
      preLoaderRoute: typeof ThinkingSlugRouteImport
      parentRoute: typeof ThinkingRoute
    }
    '/thinking/$slug/': {
      id: '/thinking/$slug/'
      path: '/'
      fullPath: '/thinking/$slug/'
      preLoaderRoute: typeof ThinkingSlugIndexRouteImport
      parentRoute: typeof ThinkingSlugRoute
    }
    '/thinking/$slug/$sub': {
      id: '/thinking/$slug/$sub'
      path: '/$sub'
      fullPath: '/thinking/$slug/$sub'
      preLoaderRoute: typeof ThinkingSlugSubRouteImport
      parentRoute: typeof ThinkingSlugRoute
    }
    '/projects/$category/$slug': {
      id: '/projects/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/projects/$category/$slug'
      preLoaderRoute: typeof ProjectsCategorySlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsCategorySlugRoute: typeof ProjectsCategorySlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsCategorySlugRoute: ProjectsCategorySlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ThinkingSlugRouteChildren {
  ThinkingSlugSubRoute: typeof ThinkingSlugSubRoute
  ThinkingSlugIndexRoute: typeof ThinkingSlugIndexRoute
}

const ThinkingSlugRouteChildren: ThinkingSlugRouteChildren = {
  ThinkingSlugSubRoute: ThinkingSlugSubRoute,
  ThinkingSlugIndexRoute: ThinkingSlugIndexRoute,
}

const ThinkingSlugRouteWithChildren = ThinkingSlugRoute._addFileChildren(
  ThinkingSlugRouteChildren,
)

interface ThinkingRouteChildren {
  ThinkingSlugRoute: typeof ThinkingSlugRouteWithChildren
  ThinkingIndexRoute: typeof ThinkingIndexRoute
}

const ThinkingRouteChildren: ThinkingRouteChildren = {
  ThinkingSlugRoute: ThinkingSlugRouteWithChildren,
  ThinkingIndexRoute: ThinkingIndexRoute,
}

const ThinkingRouteWithChildren = ThinkingRoute._addFileChildren(
  ThinkingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ThinkingRoute: ThinkingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
