/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsResidentialRouteImport } from './routes/projects.residential'
import { Route as ProjectsOthersRouteImport } from './routes/projects.others'
import { Route as ProjectsCommercialRouteImport } from './routes/projects.commercial'
import { Route as ProjectsCategorySlugRouteImport } from './routes/projects.$category.$slug'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsResidentialRoute = ProjectsResidentialRouteImport.update({
  id: '/residential',
  path: '/residential',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsOthersRoute = ProjectsOthersRouteImport.update({
  id: '/others',
  path: '/others',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCommercialRoute = ProjectsCommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsCategorySlugRoute = ProjectsCategorySlugRouteImport.update({
  id: '/$category/$slug',
  path: '/$category/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/commercial': typeof ProjectsCommercialRoute
  '/projects/others': typeof ProjectsOthersRoute
  '/projects/residential': typeof ProjectsResidentialRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/commercial': typeof ProjectsCommercialRoute
  '/projects/others': typeof ProjectsOthersRoute
  '/projects/residential': typeof ProjectsResidentialRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/people': typeof PeopleRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/commercial': typeof ProjectsCommercialRoute
  '/projects/others': typeof ProjectsOthersRoute
  '/projects/residential': typeof ProjectsResidentialRoute
  '/projects/$category/$slug': typeof ProjectsCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/people'
    | '/projects'
    | '/projects/commercial'
    | '/projects/others'
    | '/projects/residential'
    | '/projects/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/people'
    | '/projects'
    | '/projects/commercial'
    | '/projects/others'
    | '/projects/residential'
    | '/projects/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/people'
    | '/projects'
    | '/projects/commercial'
    | '/projects/others'
    | '/projects/residential'
    | '/projects/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PeopleRoute: typeof PeopleRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/residential': {
      id: '/projects/residential'
      path: '/residential'
      fullPath: '/projects/residential'
      preLoaderRoute: typeof ProjectsResidentialRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/others': {
      id: '/projects/others'
      path: '/others'
      fullPath: '/projects/others'
      preLoaderRoute: typeof ProjectsOthersRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/commercial': {
      id: '/projects/commercial'
      path: '/commercial'
      fullPath: '/projects/commercial'
      preLoaderRoute: typeof ProjectsCommercialRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$category/$slug': {
      id: '/projects/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/projects/$category/$slug'
      preLoaderRoute: typeof ProjectsCategorySlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsCommercialRoute: typeof ProjectsCommercialRoute
  ProjectsOthersRoute: typeof ProjectsOthersRoute
  ProjectsResidentialRoute: typeof ProjectsResidentialRoute
  ProjectsCategorySlugRoute: typeof ProjectsCategorySlugRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsCommercialRoute: ProjectsCommercialRoute,
  ProjectsOthersRoute: ProjectsOthersRoute,
  ProjectsResidentialRoute: ProjectsResidentialRoute,
  ProjectsCategorySlugRoute: ProjectsCategorySlugRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PeopleRoute: PeopleRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
